### ISSUE TITLE
Possible error in step 5.2.

### ISSUE THREAD

**Issue by goochjs** [RobKohr/glicko#5]
Hi,

I've been using your JavaScript implementation to compare to a Java one on which I've been working.  I think there is an error in your formula at step 5.2 of [Glickman's paper](http://www.glicko.net/glicko/glicko2.pdf) (second bullet point at the top of p3).

Line 138 of your code says:

<pre><code>if( pow(delta,2) > (pow(p.vol,2) + v) ){
    var B = ln(pow(delta,2) - pow(p.rd2,2), v);</code></pre>

I think the first line is wrong and should use the rating deviation, not the volatility.

<pre><code>if( pow(delta,2) > (pow(p.rd2,2) + v) ){
    var B = ln(pow(delta,2) - pow(p.rd2,2), v);</code></pre>

The second line also looks a bit odd as you're passing "v" into the "ln" function as a second parameter.  Shouldn't it be as follows?
<pre><code>var B = ln(pow(delta,2) - pow(p.rd2,2) - v);</pre></code>

J.

**Comment by Merudo** [comment]
Was this bug ever fixed?
